image: ruby:3.0.2

before_script:
  - cp config/database-gitlab.yml config/database.yml
  - gem install bundler
  - bundle install
  - RAILS_ENV=test bundle exec rails db:create db:migrate db:schema:load

cache:
  paths:
    - vendor/ruby

services:
  - postgres:latest

variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  CI_DB_HOST: "postgres"
  CI_USER: "postgres"
  CI_DB_PASSWORD: ""
  CI_DB_NAME: "sanctions"

stages:
  - linters
  - test

run_linters:
  stage: linters
  script:
    - bundle exec rubocop
    - bundle exec brakeman -A -k --no-skip-vendor
    - bundle-audit check --update
    - bundle exec bundler-leak check --update
    - bundle exec database_consistency

rspec:
  stage: test
  script:
    - apt-get update -qq && apt-get install -yqq nodejs
    - gem install bundler
    - bundle install -j $(nproc) --path vendor
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/