version: "3.9"
services:
  db:
    image: postgres:13.3-alpine
    container_name: sanctions-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: sanctions-es
    restart: always
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: kibana:6.8.18
    container_name: sanctions-kibana
    restart: always
    environment:
      ELASTICSEARCH_URL: "http://elastic:9200"
    ports:
      - "5601:5601"

volumes:
  db:
    driver: local
  es:
    driver: local