pre-commit:
  parallel: true
  commands:
    audit:
      run: brakeman --no-pager
    rubocop:
      files: git diff --name-only --staged
      glob: "*.rb"
      run: rubocop --force-exclusion {files}
    bundler-leak:
      run: bundle exec bundler-leak
    database_consistency:
      run: bundle exec database_consistency
    bundler-audit:
      run: bundle exec bundle-audit